export const product = [
  {
    id: "1",
    name: "BrownOff",
    gender: "man",
    pagetitle: "Patro Afero | BrownOff | NEW Summer Collection ",
    colors: ["brown", "beige", "black"],
    price: 396,
    imgName: "001.jpg",
    size: [38, 39, 40, 41, 42, 43, 44],
    title: "Brand New BrownOff have finaly arived!",
    info: "With our cool new BrownnOff you'll be the king of the castle. The sand Castle that is! Consider yourself the sexiest man on the beach with this ultimate Sandal-Sock-Combo. The materials we used for this beautifull set is a combination of pure synthetic cotton for the socks combined with a leatherlook sandal. The sandals come with a plastic footbed to provide you a firm grip during your watersport pleasure. Just remember it's Summertime, and the livin' is easy. Fish are jumpin' and the cotton is high. Oh, your daddy's rich and your ma is good lookin'. So hush, little baby, baby don't you cry.",
  },
  {
    id: "2",
    name: "BrownNosers",
    gender: "man",
    pagetitle: "Patro Afero | Brownnosers",
    colors: ["light-brown", "brown", "slightly-darker-brown", "dark-brown"],
    price: 274,
    imgName: "002.jpg",
    size: [39, 40, 41, 42, 43, 44, 45],
    title: "Brownnosers. The Office Edition.",
    info: "They've got a fine brown frame, I wonder what could be their name. They look good to me, and all I can see. Is their fine brown frame. Well wonder no more because these powerwalkers are named the Brownnoser Office Edition and they are nothing but the best for our workingclass heroes! You will be the boss of the office in notime with these Cosas Marrones. These pure leatherish sandals come with one pair of blue ánd one pair of white socks to match the collar of your dersire. Brownnosers, don't dress for the job you have. Dress for the job you want.",
  },
  {
    id: "3",
    name: "Cootie Brown",
    gender: "man",
    pagetitle: "Patro Afero | Cootie Brown",
    colors: [
      "golden brown",
      "black velvet",
      "brown sugar",
      "purple haze",
      "a whiter shade of pale",
    ],
    price: 334,
    imgName: "003.jpg",
    size: [38, 39, 40, 41, 42, 43, 44],
    title: "Cootie Brown. Not your average sandal.",
  info: "You don't simply own Cootie Browns you have to be Cootie Brown to wear them. With this in mind our designteam created this new sandal statement sensation. These flipflops are not made for those who always stay on the wagon. Nope! If you'll probaly fall off before you can wear them that's when the CB's are meant for you sir!. Our personal favorite color is the golden brow because never a frown with golden brown. But lets be honest... You look good in any color, you sexy beast. ",
  },
  {
    id: "4",
    name: "The Quick Brown Fox",
    gender: "man",
    pagetitle: "Patro Afero | The Quick Brown Fox",
    colors: ["white", "grey", "silver", "offwhite"],
    price: 389,
    imgName: "004.jpg",
    size: [38, 39, 40, 41, 42, 43],
    title: "With foxes we must play the fox...",
    info: "This stylish garment will have you jumping over anything. Lazy or not. It ain't the worst that you've seen. Can't you see what I mean? You might as well jump in and try them on. The Quixk Brown Fox will get your dad-level over ninethousand and probably make you feel bigger, better and faster than any of the other dads on the playground. To even underline this feeling of distinguishedness they come with two pair of sheepwool socks like your nana used to knit them. Remember, the prince must be a lion, but he must also know how to play the fox. Play the fox.",
  },
  {
    id: "5",
    name: "Charlie Brown",
    pagetitle: "Patro Afero | Charlie Brown",
    gender: "man",
    colors: [
      "brown (yellow socks)",
      "brown (green socks)",
      "brown (red socks)",
      "brown (blue socks)",
      "brown (pink socks)",
    ],
    price: 315,
    imgName: "005.jpg",
    size: [38, 39, 40, 41, 42, 43, 44],
    title: "Charlie Brown. Why is everybody always picking on me?",
    info: "Who's always writing on the wall? Who's always goofin' in the hall? Who's always throwin' spit balls? Guess who. Yeah, you! Who walks in the classroom, cool and slow? Who calls the English teacher Daddy-O? If that's you, you're a Charlie Brown kind of guy. Charlies obviously come in a deep dark brown leather look but since you are a joker, a smoker, a midnight toker, you'll make your statement with you colorfull socks! What about brown and green, brown and red or brown and yellow? Not to mention brown and pink for those who get their lovin' on the run.",
  },
  {
    id: "6",
    name: "Brown Bottle Flu",
    pagetitle: "Patro Afero | Brown Bottle Flu (BBF) ",
    gender: "man",
    colors: ["black it is"],
    price: 315,
    imgName: "006.jpg",
    size: [36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46],
    title: "Brown Bottle Flu",
    info: "We all know that you're badder than a-old King Kong and meaner than a junkyard dog but still, a G.O.A.T. like you gotta lean back a little from time to time. You had a rough night with the boys? Brown Bottle Flu is for you! The BBF is seriously easygoing. We made them available in only one color, black, and they come with a white sock. No more tough decisions! You already got enough on your mind. Take it easy you beautifull creature and have a Brown Bottle Flu day with this ultra comfortable synthetic combo of pure masculinity and a dash of stylish compensational behaviour.",
  },
  {
    id: "7",
    name: "The Brown Study",
    pagetitle: "Patro Afero | The Brown Study",
    gender: "man",
    colors: ["moonrock brown", "", "meteorite grey"],
    price: 299,
    imgName: "007.jpg",
    size: [ 42 ],
    title: "The Brown Study puts all academic to shame and it's here for you!",
    info: "When you are having questions of science, science and progress, then you are probably just as much of a scientists as we are. Though you don't have to be a rocketscientist to understand the following. The Brown Study is for those who want to send out a message. Are you a accademic and want to show? Than the Brown Study is the way to go. Remember when we did the moonshot? And Pony Trekker led the way? We'd move to the Canaveral moonstop. Everynaut would dance and sway. We got music in our solar system We're space truckin' round the star. Sometimes the answer lies in the size.",
  },
  {
    id: "8",
    name: "Red Right",
    pagetitle: "Patro Afero | Red Right",
    gender: "man",
    colors: ["red"],
    price: 379,
    imgName: "008.jpg",
    size: [40, 41, 42, 43, 44, 45],
    title: "Red light, Red Right?",
    info: "Take a little walk to the edge of town and go across the tracks. Where the viaduct looms, like a bird of doom as it shifts and cracks. Where secrets lie in the border fires in the humming wires. Hey man, you know you're never coming back. Past the square. Past the bridge. Past the mills, Past the stacks. On a gathering storm comes a tall handsome man. In a dusty black coat with a red right hand. Or in your case your Red Right sandals! Red Right is is build for pure powerwalking. Not ony the does color use and disgn implies speed they come with some nifty sport socks to go along! Red Right is for you speedsters!"
  },
  {
    id: "9",
    name: "Brown Sugar",
    pagetitle: "Patro Afero | Brown Sugar",
    gender: "man",
    colors: ["light brown", "brown", "dark brown"],
    price: 379,
    imgName: "009.jpg",
    size: [38, 39, 40, 41, 42, 43, 44, 45],
    title: "Dancing with Mr. Brownstone",
    info: "You get up around seven. Get outta bed around nine. You don't worry about nothin'. No. 'Cause worryin's a waste of your time. Than you should be dancing with mister Brownstone. Nothing between you toes, not even sand. You'll be  just keep tryin' to get a little better. Said a little better than before. Just start with Mr Brownstone. All the cool kids are doing it. ",
  },

  {
    id: "10",
    name: "Losers",
    pagetitle: "Patro Afero | ",
    gender: "woman",
    colors: ["dragon-scale", "snake-scale", "lizzard-scale"],
    price: 379,
    imgName: "010.jpg",
    size: [36, 37, 38, 39, 40, 41, 42],
    title: "Janis said it: Woman is Losers",
    info: "Men always seem to end up on top. They wear a nice shiny armor. Until there is a dragon for to slay. So get your own armor girl and what better place to start than at the botom? Your new Losers might give you just that little bit of advange to become a winner and reclaim your freedom! Freedom is just another word for nothing left to lose. And what do you have to lose? With Losers?",
  },
  {
    id: "11",
    name: "Florida Woman",
    pagetitle: "Patro Afero | ",
    gender: "woman",
    colors: ["black and orange", "brown and orange"],
    price: 286,
    imgName: "011.jpg",
    size: [36, 37, 38, 39, 40, 41, 42],
    title: "Florida Women.",
    info: "We love Florida women and we love the color orange. That's why the Padre Afero designeres decided to combine those passions and behold, the Florida Woman was born! A gracefull sandal with a brigth organge sock will make you the Queen of the South weither you're there or not! Deep down in Florida, well that's the place I long to be. Well, oh let me take my baby out in the backyard in the, backyard people, and sit down under the old orange tree. P.S. Buy now and get your orange bag for free!",
  },
  {
    id: "12",
    name: "Señoritas",
    pagetitle: "Patro Afero | Señoritas",
    gender: "woman",
    colors: ["Red", "orange", "yellow", "green", "blue", "indigo", "violet"],
    price: 189,
    imgName: "012.jpg",
    size: [36, 37, 38, 39, 40, 41],
    title: "That'll keep you going through the show",
    info: "We don't need no education for this one: If you don't eat your meat, you can't have any pudding! How can you have any pudding if you don't eat your meat?! What you can have is a neat pair of sandals to match your Lovely señorita. Your eyes are like stars. Your teeth are like pearls. Your ruby lips señorita. Do you ever get tired of the waiting? Then wait no more and order one of these beauties in any color of the rainbow (or two if you are feeling freaky). All sandals come with two pair of black socks.",
  },
  {
    id: "13",
    name: "Sugar Plum Fairy",
    pagetitle: "Patro Afero | Sugar Plum Fairy",
    gender: "woman",
    colors: ["pink", "purple"],
    price: 379,
    imgName: "013.jpg",
    size: [38, 39, 40, 41, 42, 43, 44, 45],
    title: "Hey babe, Take a walk on the wild side",
    info: "Lola, be the best woman you can possibly be. No need to hide it anylonger! Sugar Plum Fairy isn't your average sandal. NO MA'AM!. This is for the rebels! Have you torn your dress?  Rebel rebel, is your face a mess? Rebel rebel, how could they know? Hot tramp, we love you so! And you should love your Sugar Plum Fairy's! Order them now.",
  },
  {
    id: "14",
    name: "Truism",
    pagetitle: "Patro Afero | Truism",
    gender: "woman",
    colors: ["desert sand", "beach sand", "white beach sand", "dust"],
    price: 379,
    imgName: "014.jpg",
    size: [36, 37, 38, 39, 40, 41, 42],
    title: "long walks on the beach",
    info: "We love laughing at Padre Afero. That means going out ánd staying in. Are you that normal girl  that is always in for a good banter, just like us? Do  you like walks in the park, watching movies and going to the pub on Sunday for roast dinner? Do your friends say about you that your friends and family are realy important to you? That you are easy-going and like to stay in with a glass of wine and a DVD? Then Truim is teh Sandal for you. Truism. Our savest choice.",
  },
  {
    id: "15",
    name: "Small Steps",
    pagetitle: "Patro Afero | Small Steps for Her",
    gender: "woman",
    colors: ["white", "grey", "silver", "offwhite"],
    price: 379,
    imgName: "015.jpg",
    size: [36, 37, 38, 39, 40, 41, 42],
    title: "Big Step for mankind",
    info: "Girl, you can walk fivehundred miles in these sandals... and after that maybe even fivehundred more because these babies were made for walking! And that's just what they do. One of these days, these dandals, you'll be walking over us too. But untill then we at Patro Afero will walk those fivehundred miles with out and maybe even some more. Just to be the man who rolls a thousand miles. To fall down at your door. Go buy them! Go buy them... ",
  },
  {
    id: "16",
    name: "Old Brown",
    pagetitle: "Patro Afero | Old Brown",
    gender: "woman",
    colors: ["white", "grey", "silver", "offwhite"],
    price: 279,
    imgName: "016.jpg",
    size: [36, 37, 38, 39, 40, 41],
    title: "Comfortable as an old shoe",
    info: "Patro Afero loves all girls but we really love a short haired girl who sometimes wears it twice as long. Now we're stepping out this old brown shoe. Baby, we're in love with you. So glad you came here, it won't be the same now, we're telling you! Just try on these lovely ladies. But just like Josie, you know might know we we like out sandals a little bit older.",
  },
  {
    id: "17",
    name: "Brown Sugar",
    pagetitle: "Patro Afero | Brown Sugar ",
    gender: "woman",
    colors: ["light brown", "brown", "dark brown"],
    price: 377,
    imgName: "017.jpg",
    size: [36, 37, 38, 39, 40, 41, 42],
    title: "Dady Girls and Brown Sugar",
    info: "We bet your mama was a tent show queen and all her boyfriends were sweet sixteen. We're no schoolboys at Patro Afero we're known as daddy's, but we dó know what we like. And Brown Sugar is most definately something that we like! This sandal will make you feel like a little bit of a modern-day Disney Prinsess. A true Snowwhite. With it's brown belts and high heel you're a precious stone, you're out on your own. You know everyone in the world, but when you feel alone daddy won't let you weep. Daddy won't let you ache. Daddy gives you as much as you can take. And that's Brown Sugar with yellow socks.",
  },
  {
    id: "18",
    name: "Careahang",
    pagetitle: "Patro Afero | Carehang",
    gender: "woman",
    colors: ["white", "grey", "silver", "offwhite"],
    price: 329,
    imgName: "018.jpg",
    size: [36, 37, 38, 39, 40, 41, 42],
    title: "The one for the Rock 'n Roll Rebels! 🤘",
    info: "They couldn't see what we thought would be so obvious. They hide behind the laws they make for all of us. The ministry of truth at deals with pretense. The ministry of peace that sits on defense. You're washing your hands of what they're tryin' to do. Its for her. Careahang is for all but mostly Careahang is meant to be for you. If you are a Rock 'n Roll Rebel that does not care a hang!",
  },
];

export default product;
