export const product = [
  {
    id: "1",
    name: "BrownOff",
    gender: 'man',
    pagetitle: "Patro Afero | BrownOff | NEW Summer Collection ",
    colors: ["brown", "beige", "black"],
    price: 396,
    imgName: "001.jpg",
    size: [38, 39, 40, 41, 42, 43, 44],
    title: "Brand New BrownOff have finaly arived!",
    info: "With our cool new BrownnOff you'll be the king of the castle. The sand Castle that is! Consider yourself the sexiest man on the beach with this ultimate Sandal-Sock-Combo. The materials we used for this beautifull set is a combination of pure synthetic cotton for the socks combined with a leatherlook sandal. The sandals come with a plastic footbed to provide you a firm grip during your watersport pleasure. Just remember it's Summertime, and the livin' is easy. Fish are jumpin' and the cotton is high. Oh, your daddy's rich and your ma is good lookin'. So hush, little baby, baby don't you cry.",
  },
  {
    id: "2",
    name: "Brownnosers",
    gender: 'man',
    pagetitle: "Patro Afero | Brownnosers",
    colors: ["light-brown", "brown", "slightly-darker-brown", "dark-brown"],
    price: 274,
    imgName: "002.jpg",
    size: [39, 40, 41, 42, 43, 44, 45],
    title: "Brownnosers. The Office Edition.",
    info: "They've got a fine brown frame, I wonder what could be their name. They look good to me, and all I can see. Is their fine brown frame. Well wonder no more because these powerwalkers are named the Brownnoser Office Edition and they are nothing but the best for our workingclass heroes! You will be the boss of the office in notime with these Cosas Marrones. These pure leatherish sandals come with one pair of blue ánd a one pair of white socks to match the collar of your dersire. Brownnosers, don't dress for the job you have. Dress for the job you want.",
  },
  {
    id: "3",
    name: "Cootie Brown",
    gender: 'man',
    pagetitle: "Patro Afero | Cootie Brown",
    colors: [ "golden brown", "black velvet", "brown sugar", "purple haze", "a whiter shade of pale" ],
    price: 334,
    imgName: "003.jpg",
    size: [38, 39, 40, 41, 42, 43, 44],
    title: "Cootie Brown. Not your average sandal.",
    info: "You don't simply own Cootie Browns you have to be Cootie Brown to wear them. With this in mind our designteam created this new sandal statement sensation. They aren't made for those who always stay on the wagon. Nope! If you probaly fall off before you can wear them that's when the CB's are meant for you sir!. Our personal favorite color is the golden brown. Never a frown with golden brown. But lets be honest... all colors look the same.",
  },
  {
    id: "4",
    name: "The quick brown fox",
    gender: 'man',
    pagetitle: "Patro Afero | The Quick Brown Fox",
    colors: ["white", "grey", "silver", "offwhite"],
    price: 389,
    imgName: "004.jpg",
    size: [38, 39, 40, 41, 42, 43],
    title: "With foxes we must play the fox...",
    info: "This stylish garment will have you jumping over anything. Lazy or not. It ain't the worst that you've seen. Can't you see what I mean? You might as well jump in and try them on. The Quixk Brown Fox will get your dad-level over ninethousand and probably make you feel bigger, better and faster than any of the other dads on the playground. To even underline this feeling of distinguishedness they come with two pair of sheepwool socks like nana used to knit them. Remember, the prince must be a lion, but he must also know how to play the fox. Play the fox.",
  },
  {
    id: "5",
    name: "Charlie Brown",
    pagetitle: "Patro Afero | Charlie Brown",
    gender: 'man',
    colors: [
      "brown (yellow socks)",
      "brown (green socks)",
      "brown (red socks)",
      "brown (blue socks)",
      "brown (pink socks)",
    ],
    price: 315,
    imgName: "005.jpg",
    size: [38, 39, 40, 41, 42, 43, 44],
    title: "Charlie Brown. Why is everybody always picking on me?",
    info: "Who's always writing on the wall? Who's always goofin' in the hall? Who's always throwin' spit balls? Guess who. Yeah, you! Who walks in the classroom, cool and slow? Who calls the English teacher Daddy-O? If that's you, you're a Charlie Brown kind of guy. Charlies obviously come in a deep dark brown leather look but since you are a joker, a smoker, a midnight toker, you'll make your statement with you colorfull socks! What about brown and green, brown and red or brown and yellow? Not to mention brown and pink for those who get their lovin' on the run.",
  },
  {
    id: "6",
    name: "Brown Bottle Flu",
    pagetitle: "Patro Afero | Brown Bottle Flu (BBF) ",
    gender: 'man',
    colors: ["black it is"],
    price: 315,
    imgName: "006.jpg",
    size: [36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46],
    title: "Brown Bottle Flu",
    info: "We all know that you're badder than a-old King Kong and meaner than a junkyard dog but still, a G.O.A.T. like you gotta lean back a little some times. Xo had a rough night with the boys? Brown Bottle Flu is for you! The BBF is seriously easygoing. We made them available in only one color, black, and they come with a white sock. No more tough decisions! You alreacy  got enough on your mind. Take it easy you beautifull creature and have a Brown Bottle Flu day with this ultra comfortable synthetic combo of pure masculinity and a dash of stylish compensational behaviour.",
  },
  {
    id: "7",
    name: "The Brown Study",
    pagetitle: "Patro Afero | The Brown Study",
    gender: 'man',
    colors: ["moonrock brown", "", "meteorite grey"],
    price: 299,
    imgName: "007.jpg",
    size: [39, 40, 41, 42, 43, 44],
    title: "The Brown Study puts all academic to shame and it's here for you!",
    info: "When you are having questions of science, science and progress, then you are probably just as much of a scientists as we are. Though you don't have to be a rocketscientist to understand the following. The Brown Study is for those who want to send out a message. Are you a accademic and want to show? Than the Brown Study is the way to go. Remember when we did the moonshot? And Pony Trekker led the way? We'd move to the Canaveral moonstop. Everynaut would dance and sway. We got music in our solar system We're space truckin' round the star"
  },
  {
    id: "8",
    name: "",
    pagetitle: "Patro Afero | ",
    gender: 'man',
    colors: ["beige", "brown", "black"],
    price: 379,
    imgName: "008.jpg",
    size: [38, 39, 40, 41, 42, 43, 44, 45],
    title: "",
    info: "",
  },
  {
    id: "9",
    name: "",
    pagetitle: "Patro Afero | ",
    gender: 'man',
    colors: ["white", "grey", "silver", "offwhite"],
    price: 379,
    imgName: "009.jpg",
    size: [38, 39, 40, 41, 42, 43, 44, 45],
    title: "",
    info: "",
  },


  {
    id: "10",
    name: "",
    pagetitle: "Patro Afero | ",
    gender: 'woman',
    colors: ["white", "grey", "silver", "offwhite"],
    price: 379,
    imgName: "010.jpg",
    size: [36, 37, 38, 39, 40, 41, 42],
    title: "",
    info: "",
  },
  {
    id: "11",
    name: "",
    pagetitle: "Patro Afero | ",
    gender: 'woman',
    colors: ["white", "grey", "silver", "offwhite"],
    price: 379,
    imgName: "011.jpg",
    size: [36, 37, 38, 39, 40, 41, 42],
    title: "",
    info: "",
  },
  {
    id: "12",
    name: "",
    pagetitle: "Patro Afero | ",
    gender: 'woman',
    colors: ["white", "grey", "silver", "offwhite"],
    price: 379,
    imgName: "012.jpg",
    size: [36, 37, 38, 39, 40, 41, 42],
    title: "",
    info: "",
  },
  {
    id: "13",
    name: "",
    pagetitle: "Patro Afero | ",
    gender: 'woman',
    colors: ["white", "grey", "silver", "offwhite"],
    price: 379,
    imgName: "013.jpg",
    size: [36, 37, 38, 39, 40, 41, 42],
    title: "",
    info: "",
  },
  {
    id: "14",
    name: "",
    pagetitle: "Patro Afero | ",
    gender: 'woman',
    colors: ["white", "grey", "silver", "offwhite"],
    price: 379,
    imgName: "014.jpg",
    size: [36, 37, 38, 39, 40, 41, 42],
    title: "",
    info: "",
  },
  {
    id: "15",
    name: "",
    pagetitle: "Patro Afero | ",
    gender: 'woman',
    colors: ["white", "grey", "silver", "offwhite"],
    price: 379,
    imgName: "015.jpg",
    size: [36, 37, 38, 39, 40, 41, 42],
    title: "",
    info: "",
  },
  {
    id: "16",
    name: "",
    pagetitle: "Patro Afero | ",
    gender: 'woman',
    colors: ["white", "grey", "silver", "offwhite"],
    price: 379,
    imgName: "016.jpg",
    size: [36, 37, 38, 39, 40, 41, 42],
    title: "",
    info: "",
  },
  {
    id: "17",
    name: "",
    pagetitle: "Patro Afero | ",
    gender: 'woman',
    colors: ["white", "grey", "silver", "offwhite"],
    price: 379,
    imgName: "017.jpg",
    size: [36, 37, 38, 39, 40, 41, 42],
    title: "",
    info: "",
  },
  {
    id: "18",
    name: "",
    pagetitle: "Patro Afero | ",
    gender: 'woman',
    colors: ["white", "grey", "silver", "offwhite"],
    price: 379,
    imgName: "018.jpg",
    size: [36, 37, 38, 39, 40, 41, 42],
    title: "",
    info: "",
  },
];

export default product;
